import exceptions

result = exceptions.divide_two_numbers(2, 4)

if (result != "No integer is divisible by 0; ERROR"):
    print(result)
