#
import exception

result = exception.divide_two_numbers(2, 0)

if (result != "No integer is divisible by 0; ERROR"):
    print(result)